// export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const SET_PRICE = "SET_PRICE";
export const SET_INGREDIENTS = "SET-INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILURE = "PURCHASE_BURGER_FAILURE";

export const PURCHASE_INIT = "PURCHASE_INIT";
